name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.3"

      - name: Runs go unit tests
        run: go test -cover ./...

      - name: Sets up gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec checks
        run: gosec -exclude-dir=database ./...

      - name: Set up sqlc
        uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: "1.30.0"
      - name: Run sqlc diff
        run: sqlc diff

      - name: Run sqlc vet
        run: sqlc vet
          

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.3"

      - name: Run formatter
        run: test -z $(go fmt ./...)

      - name: Set up staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...
